Add Vagrant tests and resolve userxattr
binpash/try pull request #106
Opened 2023-07-07 18:56 UTC by ericzty

- [X] Address parts of #104 RE: (user)xattr.
- [X] Debian
- [X] Debian w/ LVM
- [X] Ubuntu
- [X] Fedora
- [X] run tests
- [ ] Rustup test
- [ ] Rebase after #99 and remove exit edit to `try`

Closes #82

2023-07-07 21:12 UTC, angelhof approved these changes
Looks good to me! Let's merge after @mgree reviews

2023-07-07 21:12 UTC, angelhof commented on Vagrantfile
> +  #Reguar debian testing box
typo :)

2023-07-11 13:27 UTC, mgree requested changes
One tiny tweak. Looks great!

2023-07-11 13:27 UTC, mgree commented on .github/workflows/vagrant.yaml
> +name: Vagrant
Might be good to have a more descriptive name (VM/distro tests?)

2023-07-11 13:27 UTC, mgree commented on .github/workflows/vagrant.yaml
> +  debian:
This is exactly what build matrices are for.

```
strategy:
  matrix:
    vagrant_target:
      - debian
      - debianrustup
      - debianlvm
      - rocky9
      - fedora33

  jobs:
    vagrant:
      runs-on: macos-latest
      steps:
        - name: Checkout
        - uses: actions/checkout@v2
         
        - name: Run VM in Vagrant
        - run: vagrant up ${{ matrix.vagrant_target }}
```

2023-07-11 17:07 UTC, merged