Add tests
binpash/try pull request #11
Opened 2023-06-01 23:25 UTC by gliargovas

Solves #2

2023-06-04 07:08 UTC, gliargovas commented
I am getting this error for a while now in the CI. It has nothing to do with the size/contents of file.txt.gz (also local tests pass). Any ideas? @mgree @angelhof 
> gzip: /home/runner/work/try/try/test/try_workspace/file.txt: Value too large for defined data type
> Running test_untar_no_flag... (!) output mismatch		FAIL

2023-06-04 12:23 UTC, mgree commented
This is an overlay issue, most likely---EOVERFLOW from a bad operation. Can you get us an strace of this?

2023-06-04 23:08 UTC, gliargovas commented
Here is the strace output of `bash ./test/run_tests.sh test_touch_and_rm_D_flag_commit`:

https://github.com/gliargovas/try/actions/runs/5171635045/jobs/9315284181#step:3:101

> This is an overlay issue, most likely---EOVERFLOW from a bad operation. Can you get us an strace of this?

2023-06-05 00:21 UTC, mgree commented
Hmm. `https://github.com/gliargovas/try/actions/runs/5171635045/jobs/9315284181#step:3:733` says:

```
wait4(-1, mount: /tmp/tmp.Ft8BAItLLD/temproot/boot: wrong fs type, bad option, bad superblock on overlay, missing codepage or helper program, or other error.
gzip: /home/runner/work/try/try/test/try_workspace/file.txt: Value too large for defined data type
[{WIFEXITED(s) && WEXITSTATUS(s) == 1}], 0, NULL) = 2432
```

What's weird here is that we're getting this `mount` error in the middle of `strace`'s reporting, which is kind of wild. Might be good to

  1. Run `strace` once for each test, rather than tracing the whole test suite.
  2. Run `mount -v` before running the tests... maybe `/boot` is a special fs? I have no idea why anyone would be touching/looking at it, though.

2023-06-05 11:29 UTC, gliargovas commented
I ran `strace` individually for each test:

https://github.com/gliargovas/try/actions/runs/5176411081/jobs/9325190327#step:3:55

2023-06-05 18:13 UTC, angelhof commented
@gliargovas remember to add a test with `git clone` after we merge #14

2023-06-12 20:05 UTC, angelhof requested changes

2023-06-12 20:05 UTC, angelhof commented on test/exit_code.sh
> +exit
This isnot correct currently because even if tests don't pass, exit will return 0. We either need to save the exit code of the tests or remove everything in the github workflow after Line 34: bash ./test/run_tests.sh

2023-06-14 06:38 UTC, gliargovas commented on test/exit_code.sh
> +exit
I will resolve this during the day :-)

2023-06-16 10:51 UTC, gliargovas commented on test/exit_code.sh
> +exit
Just fixed it!

2023-06-16 13:08 UTC, angelhof approved these changes

2023-06-16 13:08 UTC, merged