Implement Multi-Lower-Layer Overlay Support through Merging
binpash/try pull request #122
Opened 2023-10-06 22:17 UTC by gliargovas

This Pull Request introduces the `-L` flag to `try`, enabling the specification and merging of multiple lower directories for overlay. The lower directories are specified as a colon-separated list (`dir_1:dir_2:...:dir_n`), operating with a precedence logic where directories on the left have a higher precedence over those on the right. This feature allows users to overlay multiple directories together during the command execution within a single overlay environment.

2023-10-06 22:18 UTC, gliargovas commented
Should I also add some tests for this?

2023-10-07 03:01 UTC, ericzty commented on README.md
The example here is not using colon-separated list, perhaps we should choose an example that shows the list being used instead of just one dir, which we can already do.

2023-10-10 12:31 UTC, mgree requested changes
Looks good. Let's do a separate version bump once the tests pass on this.

2023-10-10 12:31 UTC, mgree commented on README.md
> +* v0.2.0 - 2023-07-24
Let's treat making a release as a separate commit.

2023-10-10 12:31 UTC, mgree commented on try
> +        while IFS="" read -r lower_dir
why not set `IFS` to `:` and use a `for` loop? should save a tempfile

2023-10-10 14:39 UTC, angelhof commented
Could you rebase this to not have Eric's and Michael's commits? Maybe you just need to start your branch from future instead of main?

2023-10-11 15:21 UTC, gliargovas commented on try
> +        while IFS="" read -r lower_dir
Makes sense, this is much simpler :-)

2023-10-11 16:58 UTC, mgree requested changes
Looks great! One small potential bug and a few small fixes (to save on processes).

2023-10-11 16:58 UTC, mgree commented on try
> +        IFS=":"
We're going to need to restore `IFS` later. Convention is to do something like:

```sh
OLDIFS="$IFS"
IFS=":"
...
IFS="$OLDIFS"
```

2023-10-11 16:58 UTC, mgree commented on try
> +    pure_mountpoint=$(echo "$mountpoint" | awk -F':' '{print $NF}')
Better to use pure sh:

```ShellSession
$ p="/:/a:/b"
$ echo ${p##*:}
/b
```

2023-10-11 16:58 UTC, mgree commented on try
> +    if [ "$pure_mountpoint" = "/" ] ||
Better to use pure shell:

```sh
case "$pure_mountpoint" in
  (/|/dev|/proc) continue;;
esac
```

2023-10-11 18:40 UTC, gliargovas commented
@mgree I have addressed all your comments. Feel free to merge!

2023-10-11 20:06 UTC, ericzty commented
before we merge, i’d like to take a bit and look into why CI is failing, i’ll try to repro this on my machines.

2023-10-11 21:47 UTC, angelhof commented on try
> +                if [ -n "$new_mountpoint" ]; then
Why is this check and if-then-else necessary?

2023-10-11 21:48 UTC, angelhof commented on try
> +    pure_mountpoint=${mountpoint##*:}
Is that the name of the mount simply without the `:`?

2023-10-11 21:49 UTC, angelhof reviewed
I left some questions :)

2023-10-11 22:12 UTC, gliargovas commented on try
> +    pure_mountpoint=${mountpoint##*:}
Yes, it is the old `mountpoint` variable. It is essentially the mountpoint of just the current sandbox instance without the merges.

2023-10-11 22:18 UTC, gliargovas commented on try
> +                if [ -n "$new_mountpoint" ]; then
This is a premature optimization. We won't perform a merge on an empty directory. I just noticed however that it added an overhead of 200ms. Without it hs works just fine, so I am removing it.

2023-10-12 18:00 UTC, mgree commented on try
> +    (/|/dev|/proc) continue;;
Conventional to indent the pattern.

2023-10-20 13:22 UTC, mgree commented
Talking with @angelhof about this, we realized there's a tricky interaction with `process_changes` when you have multiple lowerdirs: you have to replay the merge to do the comparison.

The correct solution is to mergerfs mount the layers of lowerdir and compare against _that_ merged lowerdir (rather than the `$local_file` which just absolutizes to the real system root).

But until we have a use case where someone would want to use summaries and multiple lowerdirs (`hs` doesn't want the summaries), we should punt on this and give a warning that `-L` implies `-n`.

2023-10-23 14:22 UTC, mgree commented on docs/try.1.md
> +: Show a usage message (and exit).
Can you rebase off `main`? I made some changes here already.

2023-10-31 15:21 UTC, gliargovas commented
Rebased this off `main`

2023-11-01 16:16 UTC, mgree requested changes
Nice test! I think there's some tiny argparsing fixup to do and we're good to go.

2023-11-01 16:16 UTC, mgree commented on try
> +  -L "dir1:dir2:..." specify multiple lower directories to merge (colon-separated)
add "implies -n"?

2023-11-01 16:16 UTC, mgree commented on try
> +        (L)   LOWER_DIRS="$OPTARG";;
Have it set `NO_COMMIT="quiet"`?

2023-11-01 16:16 UTC, mgree commented on docs/try.1.md
> +: Specify a colon-separated list of directories to be used as lower directories for the overlay, formatted as "dir1:dir2:...:dirn" (implies -n is used).
I think "implies -n" is clearer.

2023-11-01 16:16 UTC, mgree commented on try
>          (y)   NO_COMMIT="commit";;
Check that `-L` wasn't given already? I.e., `LOWER_DIRS` should be unset. If it's not, we need to abort: we really can't do the commit properly.

2023-11-15 07:15 UTC, gliargovas commented
@mgree, I addressed the comments you left.

2023-11-15 15:11 UTC, gliargovas commented
`Main workflow/test` is expected to fail because the workflow is changed to run `./scripts/setup.sh` in the' future' branch.

2023-11-16 16:27 UTC, gliargovas commented
Cleaned everything unrelated to this PR

2023-11-16 16:44 UTC, ericzty approved these changes
Looks good to me! :tada: :rocket: :+1:

2023-11-16 16:45 UTC, ericzty commented
Oh, is this supposed to merge into `future` or `main` branch?

2023-11-28 18:21 UTC, mgree requested changes
A few tiny nitpicks, looking good!

2023-11-28 18:21 UTC, mgree commented on try
> +            if [ -n "$new_mountpoint" ]; then
drop semi, `then` on newline?

2023-11-28 18:21 UTC, mgree commented on try
> +    (/|/dev|/proc) continue;;
indent patterns?

2023-11-28 18:21 UTC, mgree commented on try
> +Usage: $TRY_COMMAND [-nvhyx] [-i PATTERN] [-D DIR] [-U PATH] [-L "dir1:dir2:..."] CMD [ARG ...]
maybe `DIR1:DIR2:...`, without quotes?

2023-11-28 18:21 UTC, mgree commented on try
> +  -L "dir1:dir2:..." specify multiple lower directories to merge (colon-separated, implies -n)
`DIR1:DIR:...` without quotes

2023-11-28 18:21 UTC, mgree commented on try
>    -n                don't commit or prompt for commit (overrides -y)
indent all lines the same amount

2023-11-28 18:21 UTC, mgree commented on try
> +        (L)   if [ -n "$LOWER_DIRS" ]; then
no semi; `then` on new line

2023-11-28 18:21 UTC, mgree commented on try
> +                  error "the -L option has been specified multiple times." 2
no period on the end of the error message

2023-11-29 18:21 UTC, ericzty commented
Could you also rebase off latest main or add in my latest commit so CI tests pass :pray:

2024-01-13 19:47 UTC, mgree approved these changes
lgtm! thank you!!

2024-01-13 21:33 UTC, merged