feat(net): add option -x to unshare network
binpash/try pull request #130
Opened 2023-10-26 06:10 UTC by ericzty

This PR adds an option `-x` to unshare the network by adding `--net` to the first unshare invocation.

- [ ] add option to try
- [ ] add to unit test

```
eric@ide0:~/try$ ./try ip --brief link
lo               UNKNOWN        00:00:00:00:00:00 <LOOPBACK,UP,LOWER_UP>
ens18            UP             ce:b8:f6:2a:67:af <BROADCAST,MULTICAST,UP,LOWER_UP>
eric@ide0:~/try$ ./try -x ip --brief link
lo               DOWN           00:00:00:00:00:00 <LOOPBACK>
```

2023-10-27 09:53 UTC, angelhof commented on try
> +        unshare --mount --map-root-user --user --pid --fork --net "$mount_and_execute"
Could also save a variable in the `if` branch that contains `--net` and that is empty in the else branch that is then used without quotes on the unshare call. But this is OK too :)

2023-10-27 09:54 UTC, angelhof reviewed
The changes look good to me! Don't we need to also modify manpages and completions?

2023-10-27 21:48 UTC, ericzty commented on try
> +        unshare --mount --map-root-user --user --pid --fork --net "$mount_and_execute"
Done :+1:

2023-10-27 21:49 UTC, ericzty commented
> Don't we need to also modify manpages and completions?
Oops I forgot about that, they have been pushed.

2023-10-30 13:50 UTC, angelhof approved these changes
Looks good to me! Are the failing tests something to worry about?

2023-10-30 16:10 UTC, ericzty commented
> Are the failing tests something to worry about?
Likely not! They’re failing due to #128

2023-10-30 23:38 UTC, gliargovas approved these changes
LGTM! Nicely done @ericzty

2023-10-31 01:28 UTC, mgree requested changes
Looks great! Just a few small tweaks.

2023-10-31 01:28 UTC, mgree commented on docs/try.1.md
> +: Unshare the network namespace.
We can do better here---maybe, "Prevent network access (by unsharing the namespace)."

2023-10-31 01:28 UTC, mgree commented on test/network.sh
> +# Test if ping fails when network is unshared
What is `curl 1.1` supposed to do? You say `ping` but run `curl`. Maybe use `ping 8.8.8.8`?

2023-10-31 01:28 UTC, mgree commented on test/network.sh
> +if [ $? -eq 7 ]; then
no semis, use newlines:

```
if [ $? -eq 7 ]
then
  return 0
else
  return 1
fi
```

2023-10-31 01:28 UTC, mgree commented on try
> +    if [ -z "$EXTRA_NS" ]; then
I find this confusing... you set `$EXTRA_NS` but then ignore its value, hardcoding `--net`. I think it's better to set `$EXTRA_NS="--net"` and then just put it into _every_ unshare:

```
unshare --mount --map-root-user --user --pid --fork $EXTRA_NS "$mount_and_execute"
```

2023-10-31 01:28 UTC, mgree commented on try
> +  -x                unshare the network namespace
update this comment along with the manpage

2023-10-31 05:00 UTC, ericzty commented on test/network.sh
> +# Test if ping fails when network is unshared
curl 1.1 expands to curl 1.0.0.1, which gets you the frontpage of cloudflare's public dns resolver, ping doesn't work due to #131

2023-10-31 05:01 UTC, ericzty commented on try
> +    if [ -z "$EXTRA_NS" ]; then
ah, it wasn't working when i had it as "$EXTRA_NS", getting rid of the quotes works. I thought it was bad practice to not wrap them in quotes.

2023-10-31 18:23 UTC, merged