keep toplevel dir perms
binpash/try pull request #138
Opened 2024-01-10 01:33 UTC by ezrizhu

- [X] Modify try to keep toplevel dir perms
- [ ] add tests

Fixes #80

2024-02-22 18:33 UTC, ezrizhu commented on test/reuse_problematic_sandbox.sh
> +touch "$try_example_dir/temproot/etc/foo"
bin is a symlink sometimes, so they will no longer persist after try stops

2024-02-22 21:05 UTC, ezrizhu commented on try
> +    #ln -s "$sandbox_dir/temproot/$(readlink "$mountpoint")" "$sandbox_dir/temproot/$mountpoint"
oops, that was for my own comparison purposes while in development, it has been removed.

2024-02-22 21:05 UTC, ezrizhu commented on try
> +for mountpoint in $(cat "$DIRS_AND_MOUNTS")
ah that make sense, I have implemented that in the latest commit.

2024-03-05 13:11 UTC, mgree requested changes
Nice! Just a few questions.

2024-03-05 13:11 UTC, mgree commented on try
> +        if [ -d "$mountpoint" ] && [ ! -L "$mountpoint" ]
`!` goes outside `[` form

2024-03-06 22:51 UTC, ezrizhu commented on try
> +## now we deal with symlinks
Good point! This has been fixed in b9a6f6ffbaaa1ef46ccb00a64a4a9d221879f18a :3

2024-03-06 22:56 UTC, ezrizhu commented on try
> +    # remove symlink
Currently no modified things in the top level are being sync'd. Should we address this in a separate PR/issue? Working on that may require more engineering efforts. 

We're also only recreating directories and symlinks (only to directories) in the top level. No files are being recreated.

2024-03-08 16:27 UTC, mgree commented on try
> +    # remove symlink
Weird. We should add it (not nec in this PR).

2024-03-08 16:33 UTC, ezrizhu commented on try
> +    # remove symlink
Tracking in #150

2024-03-08 18:36 UTC, mgree approved these changes
Looks good to me (but maybe fix the typo, no need for re-review).

2024-03-08 18:36 UTC, mgree commented on try
> +    # first set temproot to be writible, rhel derivatives defaults / to r-xr-w-rw
Typo here in perms?

2024-03-08 20:01 UTC, merged