[WIP] gidmapping support
binpash/try pull request #145
Opened 2024-02-17 02:37 UTC by ezrizhu

(currently just using this for CI)

2024-02-22 18:35 UTC, mgree requested changes
I understand... most of this. A few more questions. I think moving the mapper into this repo is important from a supply-chain security perspective.

2024-02-22 18:35 UTC, mgree commented on setup.sh
> +wget https://github.com/ezrizhu/gidmapper/releases/download/0.0.3/gidmapper -O /usr/bin/gidmapper
We shouldn't merge this until the gidmapper is part of _this_ project.

2024-02-22 18:35 UTC, mgree commented on try
> +echo "a" > "$SOCKET"
Let's use different sentinels when sending to and receiving from the mapper---we should check that the sentinels are what we expect, too.

2024-02-22 18:35 UTC, mgree commented on try
> +              EUSER="$OPTARG"
We need to unconditionally clear `EUSER` at startup, so that it can't be invoked as `EUSER=foo try ...`. I suggest using a more specific name, like `TRYUSER`.

2024-02-22 18:35 UTC, mgree commented on try
> +    su - $EUSER -c "cd "$START_DIR" && sh $script_to_execute"
Are we confident that all of the other variables we care about are marked as export?

This should probably be `exec su ...`, since we have no other work afterwards. In fact, we could probably do `cd "$START_DIR" && exec su - ...`.

2024-02-22 18:35 UTC, mgree commented on try
> +mapper() {
Maybe a more informative name, like `uid_gid_mapper()`?

2024-02-22 18:35 UTC, mgree commented on try
> +    pid=$(pgrep -P $$ -f unshare)
Is this a new external dependency?

2024-02-22 21:10 UTC, ezrizhu commented on try
> +    pid=$(pgrep -P $$ -f unshare)
yes, we're adding libcap2-bin and procps/procps-ng. readme will be updated appropriately.
libcap2-bin for setup to do addcap to the gidmapper.
procps for pgrep to look for unshare thread id, was hoping for a non-external-dependency needed option, perhaps we can have this be built into the c gidmapper impl.

2024-02-27 19:45 UTC, mgree requested changes
notes from meeting

we need to understand the security implications before moving forward

2024-02-27 19:45 UTC, mgree commented on try
> +        gidmapper "$pid" 0 "$(id -u)" 1 0 0 65535
investigate `gidmapper "$pid" 0 "$(id -u)" 1 0 "$(id -g)" 1`? why map _all_ groups?

2024-02-27 19:45 UTC, mgree commented on try
> +    su - $EUSER -c "cd "$START_DIR" && sh $script_to_execute"
Let's add a test to ensure that:

(a) normal (non-`sudo`) use of `try` doesn't let you read files you should not have
(b) `sudo` within the normal `try` container doesn't leak privileges
(c) we need to carefully articulate how we lose privileges after having run `--map-root-user`

2024-02-27 19:48 UTC, mgree commented on try
> +
Let's make this it's own PR to unblock hs work.

2024-02-27 19:50 UTC, mgree commented on try
> +    if [ -f /.dockerenv ] && [ "$(id -u)" -eq "0" ]
Better detection `/proc/self/cgroup` or `/proc/1/cgroup` containing `docker`.

2024-02-27 19:54 UTC, mgree commented
One other test to run: can a valid `sudo`er use `sudo` inside the container? (Feels good for running scripts that need to install things, but mostly are unprivileged.)

2024-02-29 04:57 UTC, ezrizhu commented on try
> +    if [ -f /.dockerenv ] && [ "$(id -u)" -eq "0" ]
Moved to #146, /proc/self/cgroup behaves differently between cgroup1 and cgroup2. Resolved to using `df` on `mktemp -d` to check whether it is on overlayfs.

2024-02-29 04:57 UTC, ezrizhu commented on try
> +
Moved #146

2026-07-08 18:40 UTC, mgree commented
I have a new, safe approach for this that I will try to implement after OSDI.

2026-07-08 18:40 UTC, closed without merging