stdstream support
binpash/try pull request #168
Opened 2024-07-13 01:14 UTC by ezrizhu

symlinks /dev/std{in,out,err} to /proc/self/fd/{0,1,2} and cleanup after
tests included

2024-07-18 15:17 UTC, mgree requested changes
Nice! Could we add one more test that actually uses these streams, rather than just testing that the devices exist?

Here's a simple test script that reads a number `x` from stdin and outputs `2x` on stdout and `3x` on stderr:
```
read x
echo $((x * 2))
echo $((x * 3)) >&2
```
We should be able to run `echo 5 | try $SCRIPT` and get 10 on stdout and 15 on stderr. Similarly, we should be able to run `echo 5 >FILE; try $SCRIPT <FILE` (NB redir is in our shell, not in try's arg) and get the same result.

2024-07-18 15:17 UTC, mgree commented on test/stdstream.sh
> +cat > "$cmdfile" <<"EOF"
quotes are unnecessary on heredoc

2024-07-18 15:17 UTC, mgree commented on try
>  cd "$START_DIR" &&
this will set `OLDPWD` to `/dev`... any reason to not fully name `/dev/stdin`, etc.?

2024-07-19 18:32 UTC, ezrizhu commented on test/stdstream.sh
> +cat > "$cmdfile" <<"EOF"
should we also remove the quote in https://github.com/binpash/try/blob/4acc903a20f8eb2fccb5fd0cd9d1d11e64741c24/try#L132 ?

2024-07-22 21:22 UTC, ezrizhu commented
> Nice! Could we add one more test that actually uses these streams, rather than just testing that the devices exist?
> 
> Here's a simple test script that reads a number `x` from stdin and outputs `2x` on stdout and `3x` on stderr:
> 
> ```
> read x
> echo $((x * 2))
> echo $((x * 3)) >&2
> ```
> 
> We should be able to run `echo 5 | try $SCRIPT` and get 10 on stdout and 15 on stderr. Similarly, we should be able to run `echo 5 >FILE; try $SCRIPT <FILE` (NB redir is in our shell, not in try's arg) and get the same result.

That example would also pass outside of this PR since it seems like sh does not need /dev/std{in,out,err} for those streams. @mgree

2024-07-23 00:06 UTC, mgree commented
> That example would also pass outside of this PR since it seems like sh does not need /dev/std{in,out,err} for those streams. @mgree

Oh! Good point lol. Then we should write a test that uses those devices appropriately.

2024-08-07 21:15 UTC, mgree requested changes
I think this can be simpler and more precise.

2024-08-07 21:15 UTC, mgree commented on test/stdstream.sh
> +# test stdout
why not test for exact output from both at once by capturing output in `mktemp`ed files?

2024-09-06 11:37 UTC, mgree requested changes
One more test please... 🫣

2024-09-06 11:37 UTC, mgree commented on test/stdstream.sh
> +read x < /dev/stdin
Can you add one more test that uses redirects the fds directly (instead of these files)? Then we're good to go.

2024-09-06 11:37 UTC, mgree commented on try
> +ln -s /proc/self/fd/0 /dev/stdin &&
So... why does this work now? 🤔

2024-09-18 01:53 UTC, ezrizhu commented on try
> +ln -s /proc/self/fd/0 /dev/stdin &&
that has always worked, i believe the issue was something around how bash handles /dev/stdin,out,err

2024-09-18 01:55 UTC, mgree approved these changes
No diff on try stderr due to mount noise, I assume? LGTM thanks!

2024-09-18 03:17 UTC, merged