misc upperdir fixes
binpash/try pull request #169
Opened 2024-07-13 01:17 UTC by ezrizhu

some of the pure_mountpoint logic were missed when merging commits over. this PR addresses them by copying those changes from the hs branch.

2024-07-18 15:11 UTC, mgree requested changes
If this is adding new behavior, can we add a testcase for it?

2024-07-18 15:11 UTC, mgree commented on try
> +        pure_mountpoint=${mountpoint##*:}
I'm confused by this... is the list of mountpoints colon-separated/ Should we then run the loop with `IFS=":"`?

2024-07-19 18:26 UTC, ezrizhu commented on try
> +        pure_mountpoint=${mountpoint##*:}
here i just copied the pure_mountpoint logic from https://github.com/binpash/try/commit/0647f69e86eaa3bff6d9234451cdc0cd5c6030ab#diff-1e262cd7d110812f5726055a6e672b92cde43648b76adff51a12441fbdf7e667R172 if we were to change this, we should also change it elsewhere in try correct?

2024-07-23 00:03 UTC, mgree commented on try
> +        pure_mountpoint=${mountpoint##*:}
This is reading from `DIRS_AND_MOUNTS`, which is not colon separated (see line 67).

If the code's job is to remove the symlinks, we should be reading from `UPDATED_DIRS_AND_MOUNTS`. But at this point I'd really want to a test to make sure we got it right: if this wrong code passes, it means that we're not checking things. I think the correct test here would look at the sandbox temproot when we're done and ensure it's empty.

2024-08-18 03:00 UTC, ezrizhu commented on try
> +        pure_mountpoint=${mountpoint##*:}
we had tests for this, it has been failing, however, the exec bit on that was not set, so the test was never ran. now the tests pass.

2024-08-18 03:03 UTC, ezrizhu commented on test/merge_multiple_dirs.sh
can confirm this test was failing on main.

2024-08-22 02:01 UTC, mgree approved these changes
LGTM. Please write a commit message for the squashed commit that summarizes things neatly!

2024-08-22 02:08 UTC, merged