README: Add WSL install
binpash/try pull request #171
Opened 2024-08-01 10:35 UTC by Creammilky

I found overlayfs somehow are not compatible with WSL when using `try`.
**Solution:**
It can be solved by installing unionfs so I add the **WSL** subtitle in README-Installing

2024-08-07 21:17 UTC, mgree commented on README.md
> +It is highly recommended to use [unionfs](https://github.com/rpodgorny/unionfs-fuse) to run `try`.
Will `try` even work without it? Then it's not "highly recommended", but required for use on WSL!

2024-08-07 21:18 UTC, mgree requested changes
We should firm up the text here to work on all platforms (and all versions of WSL).

2024-08-07 21:18 UTC, mgree commented on README.md
> +$ sudo apt install unionfs-fuse
Debian/Ubuntu specific.

2024-08-07 21:18 UTC, mgree commented on README.md
> +```
I think this is unnecessary: we have plenty of description of how to run `try`.

2024-08-08 04:13 UTC, ezrizhu commented
and i'll take care of the CI failures.

2024-08-18 02:57 UTC, ezrizhu commented
You can merge the latest main branch now to resolve the CI failures.

2025-01-13 09:37 UTC, ezrizhu commented
closing for inactivity, if someone wishes to pick up the work, feel free to make a new PR.

2025-01-13 09:37 UTC, closed without merging