chore(doc): add archlinux installation method
binpash/try pull request #64
Opened 2023-06-25 21:49 UTC by brokenpip3

fix #61

2023-06-25 22:09 UTC, ericzty approved these changes
lg2m

2023-06-25 23:06 UTC, mgree requested changes
Two tiny typographical nits. Thank you for doing this!

2023-06-25 23:06 UTC, mgree commented on README.md
> +`Try` is present in aur, you can install it with your preferred aur helper:
nits: I think it should be "Arch Linux" and "AUR" to match what's on their websites.

2023-06-26 06:59 UTC, brokenpip3 commented on README.md
> +`Try` is present in aur, you can install it with your preferred aur helper:
looks good now? :)

2023-06-26 16:56 UTC, merged