Auto cleanup temporary files
binpash/try pull request #66
Opened 2023-06-26 00:23 UTC by zdyxry

2023-06-26 13:12 UTC, angelhof requested changes
Thank you for the changes! I left some questions that I am not sure about. In addition to that, could you add/extend a test to check that the sandbox is _not_ deleted in cases where the commit was not accepted?

2023-06-26 13:12 UTC, angelhof commented on try
> +        if [ "$exitcode" -eq 0 ] && [ "$?" -eq 0 ]
I think that a non-zero exit could could still warrant committing. What is the purpose of this change?

2023-06-26 13:12 UTC, angelhof commented on try
> +    $CLEANUP
I think that CLEANUP only needs to be called when things are committed (otherwise we delete a directory that the user might want to use later.

2023-06-26 13:12 UTC, angelhof commented on try
> +    CLEANUP="rm -rf $mount_and_execute $chroot_executable $try_mount_log"
I am not sure I would delete the try_mount_log by default it might be useful for debugging after the script is done executing. (Though admittedly now it is not shown to the user anywhere so it can't be found anyway).

2023-06-26 15:52 UTC, mgree commented on try
> +    CLEANUP="rm -rf $mount_and_execute $chroot_executable $try_mount_log"
Some branches have messages pointing to `$try_mount_log`, and we should surface it anyway.

2023-06-26 15:52 UTC, mgree commented on try
> +    $CLEANUP
I'd rather have `CLEANUP` collect the names of things to clean up and then explicitly call `rm` somewhere in the script than to collect a command and then simply run it.

2023-06-27 11:54 UTC, zdyxry commented on try
> +        if [ "$exitcode" -eq 0 ] && [ "$?" -eq 0 ]
I misunderstood here, fixed

2023-06-27 11:55 UTC, zdyxry commented on try
> +    $CLEANUP
The cleanup action is now only executed after commit

2023-06-27 11:56 UTC, zdyxry commented on try
> +    CLEANUP="rm -rf $mount_and_execute $chroot_executable $try_mount_log"
Ack.

2023-06-28 12:09 UTC, mgree commented
Okay, I'm stumped: I had a brainwave last night that we were leaving the filesystems mounted and that might be the issue... but unmounting seems to work on everything but the `/dev` mount, and we _still_ have this perms issue in the workdir. 🤔

2023-06-29 19:33 UTC, angelhof commented
Pulled the commits from this to #92, so closing this!

2023-06-29 19:33 UTC, closed without merging