[WIP] nested mount support
binpash/try pull request #67
Opened 2023-06-26 00:55 UTC by ericzty

- [X] mergerfs-fuse support
- [ ] unionfs-fuse support

2023-06-26 17:15 UTC, mgree commented
- [ ] update manpage
- [ ] update completions

😁

2023-06-29 11:19 UTC, gliargovas commented
@mgree @angelhof this is ready for review

2023-06-29 13:35 UTC, angelhof requested changes
Thanks a lot everyone! I have left some code quality comments, I can also help with fixing them if you want!

2023-06-29 13:35 UTC, angelhof commented on try
> +            if [ -z ${union_helper+x} ]; then
Is this check in here and not outside because some runs can succeed even without mergerfs or unionfs? If so, can we add a comment that we explicitly have it n here so that we don't exit prematurely if they are not needed.

2023-06-29 13:35 UTC, angelhof commented on try
> +for mointpoint in /* $(findmnt --real -r -o target -n | grep -v "^/$")
typo: mointpoint

2023-06-29 13:35 UTC, angelhof commented on try
>      ## If the directory is not a mountpoint
This comment is obsolete now.

2023-06-29 13:35 UTC, angelhof commented on try
> +        if [ "$mointpoint" = "/dev" ] || [ "$mointpoint" = "/proc" ]; then
I would suggest, making this a function and putting the logic there to not have hardcoded logic of selecting directories in main code.

```sh
should_skip_mountpoint() {
  mountpoint=$1
  [ "$mointpoint" = "/dev" ] || [ "$mointpoint" = "/proc" ]
}
```

2023-06-29 13:35 UTC, angelhof commented on try
> +        mount -t overlay overlay -o lowerdir=/"$mointpoint",upperdir="$SANDBOX_DIR"/upperdir/"$mointpoint",workdir="$SANDBOX_DIR"/workdir/"$mointpoint" "$SANDBOX_DIR"/temproot/"$mointpoint" 2>> "$try
This seems to be reused at more than one place, could we abstract it in a function, e.g.,
```sh
make_overlay() {
  sandbox_dir=$1
  mountpoint=$2
  ...
}
```

and then call it like:

```sh
make_overlay "$SANDBOX_DIR" ... 2>> "$try_mount_log"
```

2023-06-29 13:35 UTC, angelhof commented on try
> +                if command -v mergerfs > /dev/null; then
Can we abstract this code in a function, e.g., `detect_union_helper` that writes the union_helper in its stdout or nothing if it is not found. Then we can call it here with a command substitution and if the output is empty erroring out.

2023-06-29 13:35 UTC, angelhof commented on try
> +                    echo "Error: Failed to mount overlayfs normally, mergerfs or unionfs not found for $mointpoint, see $try_mount_log" 1>&2
Be consistent with the rest of the error messages w.r.t. the prefix (see https://github.com/binpash/try/blob/main/try#L139)

2023-06-29 13:35 UTC, angelhof commented on try
> +            # Here we use mergerfs/unionfs to be mounted into a single file system. Used to fix nested mounts #19
Could we explain a bit more here what we do and why it works? I could help with that too if we do a brief sync to understand how this works :)

2023-06-29 13:35 UTC, angelhof commented on try
> +for dev in tty null zero full random urandom
This should certainly go into its own function `mount_devices` or something.

2023-06-29 13:52 UTC, mgree commented on try
> +        mount -t overlay overlay -o lowerdir=/"$mointpoint",upperdir="$SANDBOX_DIR"/upperdir/"$mointpoint",workdir="$SANDBOX_DIR"/workdir/"$mointpoint" "$SANDBOX_DIR"/temproot/"$mointpoint" 2>> "$try
+1

2023-06-29 13:57 UTC, mgree commented on try
> +                    echo "Error: Failed to mount overlayfs normally, mergerfs or unionfs not found for $mointpoint, see $try_mount_log" 1>&2
I started #89 to track issues like this.

2023-06-29 14:39 UTC, angelhof commented on try
> +                    echo "Error: Failed to mount overlayfs normally, mergerfs or unionfs not found for $mointpoint, see $try_mount_log" 1>&2
Great! I will take care of some of them here (and we can leave harder/more open ended ones for a different PR) :)

2023-06-29 14:51 UTC, mgree commented on try
> +                    echo "Error: Failed to mount overlayfs normally, mergerfs or unionfs not found for $mointpoint, see $try_mount_log" 1>&2
Sounds good. I'd like to take an end-to-end pass before 0.2.0. I've been making spot improvements on various PRs, but I'd like to keep things tight. 😁  Probably won't have time until next week, though.

2023-06-29 15:05 UTC, angelhof commented on try
> +        if [ "$mointpoint" = "/dev" ] || [ "$mointpoint" = "/proc" ]; then
Actually this is OK to not do too

2023-06-29 15:52 UTC, mgree approved these changes
LGTM! Applied a few copyedits.

2023-06-29 17:07 UTC, merged