shellcheck workflow - third time is a charm
binpash/try pull request #97
Opened 2023-07-04 19:50 UTC by yamanawabi

For issue #72 

Shellcheck workflow downloads latest version from spellcheck repo. Currently, ubuntu provides 0.8.0. Latest is 0.9.0.

For try fixes:
```
In try line 68:
            mkdir -p "$SANDBOX_DIR"/upperdir/"$mountpoint" "$SANDBOX_DIR"/workdir"/$mountpoint" "$SANDBOX_DIR"/temproot/"$mountpoint"
                                                                         ^------^ SC2140 (warning): Word is of the form "A"B"C" (B indicated). Did you mean "ABC" or "A\"B\"C"?
```
Fixed issue by removing extra quotes and using curly braces with variables

```
In try line 73:
    export chroot_executable=$(mktemp)
           ^---------------^ SC2155 (warning): Declare and assign separately to avoid masking return values.
                             ^-------^ SC2046 (warning): Quote this to prevent word splitting.

In try line 74:
    export try_mount_log=$(mktemp)
           ^-----------^ SC2155 (warning): Declare and assign separately to avoid masking return values.
                         ^-------^ SC2046 (warning): Quote this to prevent word splitting.

In try line 75:
    export script_to_execute=$(mktemp)
           ^---------------^ SC2155 (warning): Declare and assign separately to avoid masking return values.
                             ^-------^ SC2046 (warning): Quote this to prevent word splitting.
```
Fixed by defining the variables and then exporting them

```
In try line 229:
            read -p "Commit these changes? [y/N] " DO_COMMIT >&2
                 ^-- SC3045 (warning): In POSIX sh, read -p is undefined.

In try line 468:
            union_helper="$OPTARG" 
            ^----------^ SC2034 (warning): union_helper appears unused. Verify use (or export if used externally).
```
Added shellcheck ignores for these in the workflow. `$union_helper` is used in the generated script, and we're dealing with Linux here specifically, so POSIX compliance is not paramount

```
In try line 470:
        (h|*) usage; exit 0;;
         ^-- SC2214 (warning): This case is not specified by getopts.
```

Added h to getops line

2023-07-05 15:14 UTC, angelhof reviewed
Great, thanks for your work! It looks good other than the minor nits that I added. No need to make a new PR, you can add new commits to this fixing the changes that I propose (than I will squash the PR into a single commit to main anyway). Once you do the changes @mgree approves it too we can merge :)

2023-07-05 15:14 UTC, angelhof commented on .github/workflows/shellcheck.yaml
> +      - name: 'Install ShellCheck package'
Could we use the github action for shellcheck instead of this? (https://github.com/marketplace/actions/shellcheck)

2023-07-05 15:14 UTC, angelhof commented on .github/workflows/shellcheck.yaml
> +          SHELLCHECK_OPTS: "-e SC2034 -e SC3045"
Could we ignore the errors inline instead of here (see https://www.shellcheck.net/wiki/Ignore) so that we don't miss other occurences of the same ones.

2023-07-05 15:14 UTC, angelhof commented on try
> +while getopts ":yvni:h:D:U:" opt
I am not sure but doesnt `:` mean that h has an option argument? i think it should be added without a `:` after it.

2023-07-06 15:41 UTC, mgree requested changes
Just a few nits---looks good, thanks!

2023-07-06 15:41 UTC, mgree commented on .github/workflows/shellcheck.yaml
> +        # ignore errors: unused variable union_helper (2034) and posix read -p (3045)
Let's use `printf` with no `\n` and a normal `read` call. On Linux, `/bin/sh`need not be bash or dash, and it's easy enough to get this right.

2023-07-12 05:14 UTC, yamanawabi commented on .github/workflows/shellcheck.yaml
> +      - name: 'Install ShellCheck package'
Ah, didn't even notice that. Will try it out.

2023-07-12 05:16 UTC, yamanawabi commented on .github/workflows/shellcheck.yaml
> +          SHELLCHECK_OPTS: "-e SC2034 -e SC3045"
Sounds good. I had them inline originally, but wasn't sure if adding the shellcheck bits would be dirty

2023-07-12 05:17 UTC, yamanawabi commented on try
> +while getopts ":yvni:h:D:U:" opt
I had the 'h' in the first block originally, but that caused the 14th (iirc) test to fail. I can dig in further to see if I can find out why it fails.

2023-07-12 05:51 UTC, yamanawabi commented
Alright, so with `getopts "yvni:D:U:"`, spellcheck passes a warning about the h being unspecified by getups: https://github.com/yamanawabi/try/actions/runs/5528024252/jobs/10084360738

With `getopts "yvnih:D:U"`, the following test fails:
https://github.com/yamanawabi/try/actions/runs/5527993006/jobs/10084295984
```/home/runner/try/try: 220: set: can't access tty; job control turned off
/tmp/tmp.pHKuXk34Ra: 1: /tmp/tmp.MLDTXG2vfr: foo1: not found
find: ‘standard output’: Broken pipe
find: write error
diff: bar.txt: No such file or directory
Running test_ignore_flag... non-zero ec (2)		FAIL```

all other requests have been fixed up

2023-07-12 15:05 UTC, angelhof approved these changes
Tiny nit! Looks good otherwise, thanks for the help!

2023-07-12 15:05 UTC, angelhof commented on try
> +        if [ -d "$mountpoint" ]; then
Nit: Could you revert this to a newline instead of a semicolon between the condition and the `then`? We are trying to keep the code consistent :)
```sh
if [ -d "$mountpoint" ]
then
```

2023-07-13 17:08 UTC, merged

2023-07-13 17:13 UTC, yamanawabi commented
thanks for making the fix and merging!